version: "3.9"
services:

    wordpress:
        container_name: wordpress
        image: wordpress:php8.2-apache
        restart: always
        stdin_open: true
        tty: true
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: "${DB_USER}"
            WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
            WORDPRESS_DB_NAME: "${DB_NAME}"
        volumes:
            - ./public_html:/var/www/html
            - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
            ]
        ports:
            - 3306
        volumes:
            - db_data:/var/lib/mysql
            - ./db_dump:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            UPLOAD_LIMIT: 50M
        ports:
            - 8080
        links:
            - mysql:mysql

    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./certbot/conf:/etc/nginx/ssl
            - ./public_html:/var/www/html

    certbot:
        container_name: certbot
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/html --email it@generalmagic.io --agree-tos --no-eff-email -d retropgf.com -d www.retropgf.com
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data:/var/www/html

volumes:
    db_data:
